### ISSUE TITLE
Holy Grail Layout

### ISSUE THREAD

**Issue by ajthyng** [txstate-etc/txstate-components#12]
Every time a project is instantiated there's some initial setup to be done to get the page layout correct. This should be controlled by a simple reusable and configurable component.

https://en.wikipedia.org/wiki/Holy_grail_(web_design)

* Layout component should have a Header, Footer, Sidebar, Content, and Fixed Right Sidebar.
* Any of the options should be usable in any combination, for instance a site could have just a Header and Content area, only a Content area, or a Content and Sidebar area.

**Comment by wickning1** [comment]
I think the right sidebar should be omitted in favor of another component that helps content components draw panels. So the typical pattern would be:

- Layout
  - Header extra content (hopefully minimal, passed as prop or named slot)
  - Nav content (passed as prop or named slot)
  - MyCustomEditorInterface (main slot)
    - Panels
      - MyCustomEditorViewArea (passed as prop or named slot, to be placed on the left)
      - MyCustomEditorActionArea (passed as prop or named slot, to be placed on the right)
  - Footer extra content (hopefully minimal, passed as prop or named slot)

If the Layout component draws the right sidebar, we end up having to pass state around or do DOM manipulation to feed content to it.  I believe the vast majority of the time we'd want MyCustomEditorInterface to be able to manage the right side of the screen with nothing but its own state.

**Comment by wickning1** [comment]
I made a [panel helper](https://git.txstate.edu/its/change-ui/blob/d4596aabf3b6ac0ca9550e094602652b7ebf7e69/src/components/AlternateListEditor/PaneManager.js) in change-ui.

The nice thing about it is it was able to handle responsiveness, so that the right panel just takes over when it's active and the screen is small. When the screen is large, it pops out and takes up the right half.  I think it was a pretty good pattern for filters and edit forms and the like.  

That particular one also allowed adding an optional gray overlay over the left panel to disable it.  That's something we can play with, but the point is that there's plenty for a panel helper to do to justify its existence.

**Comment by ajthyng** [comment]
That's essentially what I was picturing as well. The way you're describing the panel you made is also how the Panel in office-ui-fabric-react works.
